# Generated by Django 5.0.6 on 2024-06-09 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('link', models.URLField()),
                ('section', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Applicationlink',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Userslogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Userslogin',
            },
        ),
        migrations.CreateModel(
            name='Assignsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.ManyToManyField(to='link.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='link.userslogin')),
            ],
            options={
                'db_table': 'user_data_table',
            },
        ),
    ]
